<?php

namespace PersonasBundle\Entity;

/**
 * EmpleadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmpleadoRepository extends \Doctrine\ORM\EntityRepository {

    public function getEmpleadoByApellido($apellido) {
        $qb = $this->createQueryBuilder('e');
        $qb
                ->join('e.personaTipo', 'pt')
                ->join('pt.persona', 'pers')
                ->where("upper(pers.apellido) like upper(:apellido)");

        $qb->setParameter('apellido', '%' . $apellido . '%');

        return $qb->getQuery()->getResult();
    }

}
