agente_inicio_patente:
    path:     /
    defaults: { _controller: "VehiculosBundle:AgenteInicioPatente:index" }

agente_inicio_patente_show:
    path:     /{id}/show
    defaults: { _controller: "VehiculosBundle:AgenteInicioPatente:show" }

agente_inicio_patente_new:
    path:     /new
    defaults: { _controller: "VehiculosBundle:AgenteInicioPatente:new" }

agente_inicio_patente_create:
    path:     /create
    defaults: { _controller: "VehiculosBundle:AgenteInicioPatente:create" }
    methods:  POST

agente_inicio_patente_edit:
    path:     /{id}/edit
    defaults: { _controller: "VehiculosBundle:AgenteInicioPatente:edit" }

agente_inicio_patente_update:
    path:     /{id}/update
    defaults: { _controller: "VehiculosBundle:AgenteInicioPatente:update" }
    methods:  [POST, PUT]

agente_inicio_patente_delete:
    path:     /{id}/delete
    defaults: { _controller: "VehiculosBundle:AgenteInicioPatente:delete" }
    methods:  [POST, DELETE]
