get_muestra_campos_plan_de_ahorro:
    path:     /get_muestra_campos_plan_de_ahorro
    defaults: { _controller: "VehiculosBundle:Ajax:getMuestraCamposPlanDeAhorro" }   
    
movimiento_deposito_create_ajax:
    path:     /movimiento_deposito_create_ajax/
    defaults: { _controller: "VehiculosBundle:Ajax:movimientoDepositoCreateAjax" }
    
new_movimiento_deposito_ajax:
    path:     /new_movimiento_deposito_ajax/{vehiculoId}
    defaults: { _controller: "VehiculosBundle:Ajax:newMovimientoDeposito" }     
    
get_fotos_danios_gm_ajax:
    path:     /get_fotos_danios_gm_ajax/danioId
    defaults: { _controller: "VehiculosBundle:Ajax:getFotosDaniosGm" }

get_tipo_danios_internos:
    path:     /get_tipo_danios_internos
    defaults: { _controller: "VehiculosBundle:Ajax:getTipoDanioInterno" }
    
get_fotos_danios_interno_ajax:
    path:     /get_fotos_danios_interno_ajax/danioId
    defaults: { _controller: "VehiculosBundle:Ajax:getFotosDaniosInterno" }    
    
get_slug_estado_patentamiento_ajax:
    path:     /get_slug_estado_patentamiento_ajax/estadoPatentamiendoId
    defaults: { _controller: "VehiculosBundle:Ajax:getSlugEstadoPatentamiento" }     
 
new_registro_pago_a_gm_ajax:
    path:     /new_registro_pago_a_gm_ajax/{vehiculoId}
    defaults: { _controller: "VehiculosBundle:Ajax:newRegistroPagoAGmAjax" }

pago_a_gm_update_ajax:
    path:     /pago_a_gm_update_ajax/{vehiculoId}
    defaults: { _controller: "VehiculosBundle:Ajax:pagoAGmUpdateAjax" }    
    
new_asignacion_vehiculo_ajax:
    path:     /new_asignacion_vehiculo_ajax/{vehiculoId}
    defaults: { _controller: "VehiculosBundle:Ajax:newAsignacionVehiculoAjax" }

asignacion_vehiculo_update_ajax:
    path:     /asignacion_vehiculo_update_ajax/{vehiculoId}
    defaults: { _controller: "VehiculosBundle:Ajax:asignacionVehiculoUpdateAjax" }        
  
new_agenda_entrega_ajax:
    path:     /new_agenda_entrega_ajax/{vehiculoId}
    defaults: { _controller: "VehiculosBundle:Ajax:newAgendaEntregaAjax" }

agenda_entrega_create_ajax:
    path:     /agenda_entrega_create_ajax/{vehiculoId}
    defaults: { _controller: "VehiculosBundle:Ajax:agendaEntregaCreateAjax" }     