get_muestra_campos_plan_de_ahorro:
    path:     /get_muestra_campos_plan_de_ahorro
    defaults: { _controller: "VehiculosBundle:Ajax:getMuestraCamposPlanDeAhorro" }   
    
movimiento_deposito_create_ajax:
    path:     /movimiento_deposito_create_ajax/
    defaults: { _controller: "VehiculosBundle:Ajax:movimientoDepositoCreateAjax" }
    
new_movimiento_deposito_ajax:
    path:     /new_movimiento_deposito_ajax/{vehiculoId}
    defaults: { _controller: "VehiculosBundle:Ajax:newMovimientoDeposito" }     