check_control_interno_resultado_cabecera:
    path:     /
    defaults: { _controller: "VehiculosBundle:CheckControlInternoResultadoCabecera:index" }

check_control_interno_resultado_cabecera_show:
    path:     /{id}/show
    defaults: { _controller: "VehiculosBundle:CheckControlInternoResultadoCabecera:show" }

check_control_interno_resultado_cabecera_new:
    path:     /new
    defaults: { _controller: "VehiculosBundle:CheckControlInternoResultadoCabecera:new" }

check_control_interno_resultado_cabecera_create:
    path:     /create
    defaults: { _controller: "VehiculosBundle:CheckControlInternoResultadoCabecera:create" }
    methods:  POST

check_control_interno_resultado_cabecera_edit:
    path:     /{id}/edit
    defaults: { _controller: "VehiculosBundle:CheckControlInternoResultadoCabecera:edit" }

check_control_interno_resultado_cabecera_update:
    path:     /{id}/update
    defaults: { _controller: "VehiculosBundle:CheckControlInternoResultadoCabecera:update" }
    methods:  [POST, PUT]

check_control_interno_resultado_cabecera_delete:
    path:     /{id}/delete
    defaults: { _controller: "VehiculosBundle:CheckControlInternoResultadoCabecera:delete" }
    methods:  [POST, DELETE]
