codigos_danios_gm:
    path:     /
    defaults: { _controller: "VehiculosBundle:CodigoDanioGm:index" }

codigos_danios_gm_show:
    path:     /{id}/show
    defaults: { _controller: "VehiculosBundle:CodigoDanioGm:show" }

codigos_danios_gm_new:
    path:     /new
    defaults: { _controller: "VehiculosBundle:CodigoDanioGm:new" }

codigos_danios_gm_create:
    path:     /create
    defaults: { _controller: "VehiculosBundle:CodigoDanioGm:create" }
    methods:  POST

codigos_danios_gm_edit:
    path:     /{id}/edit
    defaults: { _controller: "VehiculosBundle:CodigoDanioGm:edit" }

codigos_danios_gm_update:
    path:     /{id}/update
    defaults: { _controller: "VehiculosBundle:CodigoDanioGm:update" }
    methods:  [POST, PUT]

codigos_danios_gm_delete:
    path:     /{id}/delete
    defaults: { _controller: "VehiculosBundle:CodigoDanioGm:delete" }
    methods:  [POST, DELETE]
