factura:
    path:     /
    defaults: { _controller: "VehiculosBundle:Factura:index" }

factura_show:
    path:     /{id}/show
    defaults: { _controller: "VehiculosBundle:Factura:show" }

factura_new:
    path:     /new
    defaults: { _controller: "VehiculosBundle:Factura:new" }

factura_create:
    path:     /create
    defaults: { _controller: "VehiculosBundle:Factura:create" }
    methods:  POST

factura_edit:
    path:     /{id}/edit
    defaults: { _controller: "VehiculosBundle:Factura:edit" }

factura_update:
    path:     /{id}/update
    defaults: { _controller: "VehiculosBundle:Factura:update" }
    methods:  [POST, PUT]

factura_delete:
    path:     /{id}/delete
    defaults: { _controller: "VehiculosBundle:Factura:delete" }
    methods:  [POST, DELETE]
