index_repote_autos_vendidos_por_vendedor:
    path:     /index_repote_autos_vendidos_por_vendedor
    defaults: { _controller: "VehiculosBundle:Reporte:indexReporteAutosVendidosPorVendedor" }

exportart_pdf_repote_autos_vendidos_por_vendedor:
    path:     /exportart_pdf_repote_autos_vendidos_por_vendedor
    defaults: { _controller: "VehiculosBundle:Reporte:pdfReporteAutosVendidosPorVendedor" }

exportart_excel_repote_autos_vendidos_por_vendedor:
    path:     /exportart_excel_repote_autos_vendidos_por_vendedor
    defaults: { _controller: "VehiculosBundle:Reporte:excelReporteAutosVendidosPorVendedor" }
    
index_reporte_vehiculos_en_stock:
    path:     /index_reporte_vehiculos_en_stock
    defaults: { _controller: "VehiculosBundle:Reporte:indexReporteVehiculosEnStock" }

exportar_pdf_reporte_vehiculos_en_stock:
    path:     /exportar_pdf_repote_vehiculos_en_stock
    defaults: { _controller: "VehiculosBundle:Reporte:pdfReporteVehiculosEnStock" }

exportar_excel_reporte_vehiculos_en_stock:
    path:     /exportar_excel_reporte_vehiculos_en_stock
    defaults: { _controller: "VehiculosBundle:Reporte:excelReporteVehiculosEnStock" }   
    
index_reporte_agenda_entregas:
    path:     /index_reporte_agenda_entregas
    defaults: { _controller: "VehiculosBundle:Reporte:IndexReporteAgendaEntregas" }

exportar_pdf_reporte_agenda_entregas:
    path:     /exportar_pdf_reporte_agenda_entregas
    defaults: { _controller: "VehiculosBundle:Reporte:pdfReporteAgendaEntregas" }

exportar_excel_reporte_agenda_entregas:
    path:     /exportar_excel_reporte_agenda_entregas
    defaults: { _controller: "VehiculosBundle:Reporte:excelReporteAgendaEntregas" }      

resumen_vehiculo_pdf:
    path:     /{vehiculoId}/resumen_vehiculo_pdf
    defaults: { _controller: "VehiculosBundle:Reporte:ResumenVehiculoPdf" }

index_reporte_vehiculos_cupon_garantia:
    path:     /index_reporte_vehiculos_cupon_garantia
    defaults: { _controller: "VehiculosBundle:Reporte:indexReporteVehiculosCuponGarantia" }

exportar_pdf_reporte_vehiculos_cupon_garantia:
    path:     /exportar_pdf_reporte_vehiculos_cupon_garantia
    defaults: { _controller: "VehiculosBundle:Reporte:pdfReporteVehiculosCuponGarantia" }

exportar_excel_reporte_vehiculos_cupon_garantia:
    path:     /exportar_excel_reporte_vehiculos_cupon_garantia
    defaults: { _controller: "VehiculosBundle:Reporte:excelReporteVehiculosCuponGarantia" }

index_reporte_vehiculos_con_danios:
    path:     /index_reporte_vehiculos_con_danios
    defaults: { _controller: "VehiculosBundle:Reporte:indexReporteVehiculosRecibidosConDanios" }

exportar_pdf_reporte_vehiculos_con_danios:
    path:     /exportar_pdf_reporte_vehiculos_con_danios
    defaults: { _controller: "VehiculosBundle:Reporte:pdfReporteVehiculosRecibidosConDanios" }

exportar_excel_reporte_vehiculos_con_danios:
    path:     /exportar_excel_reporte_vehiculos_con_danios
    defaults: { _controller: "VehiculosBundle:Reporte:excelReporteVehiculosRecibidosConDanios" }
    
pdf_check_control_interno:
    path:     /pdf_check_control_interno{vehiculoId}
    defaults: { _controller: "VehiculosBundle:Reporte:pdfCheckControlInterno" }    

index_reporte_vehiculos_con_danios_internos:
    path:     /index_reporte_vehiculos_con_danios_internos
    defaults: { _controller: "VehiculosBundle:Reporte:indexReporteVehiculosConDaniosInternos" }

exportar_pdf_reporte_vehiculos_con_danios_internos:
    path:     /exportar_pdf_reporte_vehiculos_con_danios_internos
    defaults: { _controller: "VehiculosBundle:Reporte:pdfReporteVehiculosConDaniosInternos" }

exportar_excel_reporte_vehiculos_con_danios_internos:
    path:     /exportar_excel_reporte_vehiculos_con_danios_internos
    defaults: { _controller: "VehiculosBundle:Reporte:excelReporteVehiculosConDaniosInternos" }

index_reporte_vehiculos_por_deposito:
    path:     /index_reporte_vehiculos_por_deposito
    defaults: { _controller: "VehiculosBundle:Reporte:indexReporteVehiculosPorDeposito" }

exportar_pdf_reporte_vehiculos_por_deposito:
    path:     /exportar_pdf_reporte_vehiculos_por_deposito
    defaults: { _controller: "VehiculosBundle:Reporte:pdfReporteVehiculosPorDeposito" }

exportar_excel_reporte_vehiculos_por_deposito:
    path:     /exportar_excel_reporte_vehiculos_por_deposito
    defaults: { _controller: "VehiculosBundle:Reporte:excelReporteVehiculosPorDeposito" }     

index_reporte_vehiculos_patentamientos:
    path:     /index_reporte_vehiculos_patentamientos
    defaults: { _controller: "VehiculosBundle:Reporte:indexReporteVehiculosPatentamientos" }

exportar_pdf_reporte_vehiculos_patentamientos:
    path:     /exportar_pdf_reporte_vehiculos_patentamientos
    defaults: { _controller: "VehiculosBundle:Reporte:pdfReporteVehiculosPatentamientos" }

exportar_excel_reporte_vehiculos_patentamientos:
    path:     /exportar_excel_reporte_vehiculos_patentamientos
    defaults: { _controller: "VehiculosBundle:Reporte:excelReporteVehiculosPatentamientos" }

index_reporte_vehiculos_asignados_a_reventa:
    path: /index_reporte_vehiculos_asignados_a_reventa
    defaults: { _controller: "VehiculosBundle:Reporte:indexReporteVehiculosAsignadosAReventa" }

exportar_pdf_reporte_vehiculos_asignados_reventa:
    path:     /exportar_pdf_reporte_vehiculos_asignados_reventa
    defaults: { _controller: "VehiculosBundle:Reporte:pdfReporteVehiculosAsignadosAReventa" }

exportar_excel_reporte_vehiculos_asignados_reventa:
    path:     /exportar_excel_reporte_vehiculos_asignados_reventa
    defaults: { _controller: "VehiculosBundle:Reporte:excelReporteVehiculosAsignadosAReventa" }