tipo_compra:
    path:     /
    defaults: { _controller: "VehiculosBundle:TipoCompra:index" }

tipo_compra_show:
    path:     /{id}/show
    defaults: { _controller: "VehiculosBundle:TipoCompra:show" }

tipo_compra_new:
    path:     /new
    defaults: { _controller: "VehiculosBundle:TipoCompra:new" }

tipo_compra_create:
    path:     /create
    defaults: { _controller: "VehiculosBundle:TipoCompra:create" }
    methods:  POST

tipo_compra_edit:
    path:     /{id}/edit
    defaults: { _controller: "VehiculosBundle:TipoCompra:edit" }

tipo_compra_update:
    path:     /{id}/update
    defaults: { _controller: "VehiculosBundle:TipoCompra:update" }
    methods:  [POST, PUT]

tipo_compra_delete:
    path:     /{id}/delete
    defaults: { _controller: "VehiculosBundle:TipoCompra:delete" }
    methods:  [POST, DELETE]
