vehiculos:
    path:     /
    defaults: { _controller: "VehiculosBundle:Vehiculo:index" }

vehiculos_show:
    path:     /{id}/show
    defaults: { _controller: "VehiculosBundle:Vehiculo:show" }

vehiculos_new:
    path:     /new
    defaults: { _controller: "VehiculosBundle:Vehiculo:new" }

vehiculos_create:
    path:     /create
    defaults: { _controller: "VehiculosBundle:Vehiculo:create" }
    methods:  POST

vehiculos_edit:
    path:     /{id}/edit
    defaults: { _controller: "VehiculosBundle:Vehiculo:edit" }

vehiculos_update:
    path:     /{id}/update
    defaults: { _controller: "VehiculosBundle:Vehiculo:update" }
    methods:  [POST, PUT]

vehiculos_delete:
    path:     /{id}/delete
    defaults: { _controller: "VehiculosBundle:Vehiculo:delete" }
    methods:  [POST, DELETE]

vehiculos_alta:
    path:     /alta
    defaults: { _controller: "VehiculosBundle:Vehiculo:alta" }

vehiculos_actualizar_remito:
    path:     /{vehiculoId}/vehiculos_actualizar_remito
    defaults: { _controller: "VehiculosBundle:Vehiculo:actualizarVehiculoRemito" }
    
vehiculos_pendientes_index:
    path:     /vehiculos_pendientes_index
    defaults: { _controller: "VehiculosBundle:Vehiculo:vehiculosPendientesIndex" } 
    
vehiculos_recibidos_index:
    path:     /vehiculos_recibidos_index
    defaults: { _controller: "VehiculosBundle:Vehiculo:vehiculosRecibidosIndex" }

vehiculos_editar_recibido:
    path:     /{vehiculoId}/vehiculos_editar_recibido
    defaults: { _controller: "VehiculosBundle:Vehiculo:editarVehiculoRecibido" }

   