<?php

namespace VehiculosBundle\Entity\Repository;

/**
 * TipoEstadoDanioGmRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoEstadoDanioGmRepository extends \Doctrine\ORM\EntityRepository
{
}
