sucursales:
    path:     /
    defaults: { _controller: "EmpresasBundle:Sucursal:index" }

sucursales_show:
    path:     /{id}/show
    defaults: { _controller: "EmpresasBundle:Sucursal:show" }

sucursales_new:
    path:     /new
    defaults: { _controller: "EmpresasBundle:Sucursal:new" }

sucursales_create:
    path:     /create
    defaults: { _controller: "EmpresasBundle:Sucursal:create" }
    methods:  POST

sucursales_edit:
    path:     /{id}/edit
    defaults: { _controller: "EmpresasBundle:Sucursal:edit" }

sucursales_update:
    path:     /{id}/update
    defaults: { _controller: "EmpresasBundle:Sucursal:update" }
    methods:  [POST, PUT]

sucursales_delete:
    path:     /{id}/delete
    defaults: { _controller: "EmpresasBundle:Sucursal:delete" }
    methods:  [POST, DELETE]
