vehiculos_check_control_interno_resultado_cabecera:
    resource: "@VehiculosBundle/Resources/config/routing/checkcontrolinternoresultadocabecera.yml"
    prefix:   /check_control_interno_resultado_cabecera

vehiculos_check_control_interno_pregunta:
    resource: "@VehiculosBundle/Resources/config/routing/checkcontrolinternopregunta.yml"
    prefix:   /check_control_interno_pregunta

vehiculos_tipo_danio_interno:
    resource: "@VehiculosBundle/Resources/config/routing/tipodaniointerno.yml"
    prefix:   /tipo_danio_interno

vehiculos_categoria_danio_interno:
    resource: "@VehiculosBundle/Resources/config/routing/categoriadaniointerno.yml"
    prefix:   /categoria_danio_interno

vehiculos_tipo_estado_danio_gm:
    resource: "@VehiculosBundle/Resources/config/routing/tipoestadodaniogm.yml"
    prefix:   /tipo_estado_danio_gm

vehiculos_movimiento_deposito:
    resource: "@VehiculosBundle/Resources/config/routing/movimientodeposito.yml"
    prefix:   /movimiento_deposito

vehiculos_tipo_movimiento:
    resource: "@VehiculosBundle/Resources/config/routing/tipomovimiento.yml"
    prefix:   /tipo_movimiento

vehiculos_depositos:
    resource: "@VehiculosBundle/Resources/config/routing/deposito.yml"
    prefix:   /depositos

vehiculos_transportistas:
    resource: "@VehiculosBundle/Resources/config/routing/transportista.yml"
    prefix:   /transportistas

vehiculos_codigo_modelo:
    resource: "@VehiculosBundle/Resources/config/routing/codigomodelo.yml"
    prefix:   /codigo_modelo

vehiculos_nombre_modelo:
    resource: "@VehiculosBundle/Resources/config/routing/nombremodelo.yml"
    prefix:   /nombre_modelo

vehiculos_gravedad_danios_gm:
    resource: "@VehiculosBundle/Resources/config/routing/gravedaddaniogm.yml"
    prefix:   /gravedad_danios_gm

vehiculos_codigos_danios_gm:
    resource: "@VehiculosBundle/Resources/config/routing/codigodaniogm.yml"
    prefix:   /codigos_danios_gm

vehiculos_tipos_danios_gm:
    resource: "@VehiculosBundle/Resources/config/routing/tipodaniogm.yml"
    prefix:   /tipos_danios_gm

vehiculos_tipo_venta_especial:
    resource: "@VehiculosBundle/Resources/config/routing/tipoventaespecial.yml"
    prefix:   /tipo_venta_especial

vehiculos_remitos:
    resource: "@VehiculosBundle/Resources/config/routing/remito.yml"
    prefix:   /remitos

vehiculos_tipo_estado_vehiculo:
    resource: "@VehiculosBundle/Resources/config/routing/tipoestadovehiculo.yml"
    prefix:   /tipo_estado_vehiculo

vehiculos_vehiculos:
    resource: "@VehiculosBundle/Resources/config/routing/vehiculo.yml"
    prefix:   /vehiculos

vehiculos_ajax:
    resource: "@VehiculosBundle/Resources/config/routing/ajax.yml"
    prefix:   /ajax

vehiculos_homepage:
    path:     /hello/{name}
    defaults: { _controller: VehiculosBundle:Default:index }
