services:
    manager.vehiculos:
        class: VehiculosBundle\Services\VehiculosManager
        arguments:
            container: '@service_container'
        tags:
            - { name: manager.vehiculos, alias: manager.vehiculos }

    manager.reportes:
        class: VehiculosBundle\Services\ReportesManager
        arguments:
            container: '@service_container'
        tags:
            - { name: manager.reportes, alias: manager.reportes }

    manager.notificaciones:
            class: VehiculosBundle\Services\NotificacionesManager
            arguments:
                container: '@service_container'
            tags:
                - { name: manager.notificaciones, alias: manager.notificaciones }
