crm_ajax:
    resource: "@CRMBundle/Resources/config/routing/ajax.yml"
    prefix:   /ajax

crm_preguntas:
    resource: "@CRMBundle/Resources/config/routing/encuestapregunta.yml"
    prefix:   /preguntas

crm_encuesta:
    resource: "@CRMBundle/Resources/config/routing/encuesta.yml"
    prefix:   /encuesta

crm_reporte_encuesta:
    path:   /reporte_encuesta
    defaults: { _controller: "CRMBundle:CRMDefault:reporteEncuestasRealizadas" }

crm_ver_encuesta_realizada:
    path:     /ver_encuesta_realizada/{resultadoCabeceraId}
    defaults: { _controller: CRMBundle:CRMDefault:verEncuesta }

crm_encuestas_realizadas:
    path:     /encuestas_realizadas
    defaults: { _controller: CRMBundle:CRMDefault:indexEncuestasRealizadas }

crm_homepage:
    path:     /
    defaults: { _controller: CRMBundle:CRMDefault:index }
