services:
#    crm.example:
#        class: CRMBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    manager.crm_encuestas:
        class: CRMBundle\Services\CRMEncuestasManager
        arguments:
            em: '@doctrine.orm.entity_manager'
            tags:
                - { name: manager.crm_encuestas, alias: manager.crm_encuestas }