services:
#    crm.example:
#        class: CRMBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    form.type.crmbundle_encuestapregunta:
        class: CRMBundle\Form\EncuestaPreguntaType
        tags:
            - { name: form.type, alias: crmbundle_encuestapregunta }