<?php

namespace VehiculosBundle\Entity;

/**
 * VehiculoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VehiculoRepository extends \Doctrine\ORM\EntityRepository
{
}
