<?php

namespace VehiculosBundle\Entity;

/**
 * VehiculoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VehiculoRepository extends \Doctrine\ORM\EntityRepository {

    public function getVehiculosEstado($estado) {
        $qb = $this->createQueryBuilder('p');

        $qb->join('p.estadoVehiculo', 'ev');
        $qb->andWhere('ev.tipoEstadoVehiculo = :estado')
                ->setParameter('estado', $estado);
        $qb->andWhere('ev.actual = true');
        $qb->setMaxResults(1000);

        return $qb->getQuery()->getResult();
    }

}
