app_item_aplicativo:
    resource: "@AppBundle/Resources/config/routing/itemaplicativo.yml"
    prefix:   /item_aplicativo

app_aplicativo:
    resource: "@AppBundle/Resources/config/routing/aplicativo.yml"
    prefix:   /aplicativo

app_homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

app_pantalla_vacia:
    path: /app_pantalla_vacia
    defaults: { _controller: "AppBundle:Default:pantallaVacia" }
