services:
#    app.example:
#        class: AppBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    manager.app:
            class: AppBundle\Services\AppManager
            arguments:
                router: "@router"
            tags:
                - { name: manager.app, alias: manager.app }