departamento:
    path:     /
    defaults: { _controller: "UbicacionBundle:Departamento:index" }

departamento_show:
    path:     /{id}/show
    defaults: { _controller: "UbicacionBundle:Departamento:show" }

departamento_new:
    path:     /new
    defaults: { _controller: "UbicacionBundle:Departamento:new" }

departamento_create:
    path:     /create
    defaults: { _controller: "UbicacionBundle:Departamento:create" }
    requirements: { _method: post }

departamento_edit:
    path:     /{id}/edit
    defaults: { _controller: "UbicacionBundle:Departamento:edit" }

departamento_update:
    path:     /{id}/update
    defaults: { _controller: "UbicacionBundle:Departamento:update" }
    requirements: { _method: post|put }

departamento_delete:
    path:     /{id}/delete
    defaults: { _controller: "UbicacionBundle:Departamento:delete" }
    requirements: { _method: post|delete }
