pais:
    path:     /
    defaults: { _controller: "UbicacionBundle:Pais:index" }

pais_show:
    path:     /{id}/show
    defaults: { _controller: "UbicacionBundle:Pais:show" }

pais_new:
    path:     /new
    defaults: { _controller: "UbicacionBundle:Pais:new" }

pais_create:
    path:     /create
    defaults: { _controller: "UbicacionBundle:Pais:create" }
    requirements: { _method: post }

pais_edit:
    path:     /{id}/edit
    defaults: { _controller: "UbicacionBundle:Pais:edit" }

pais_update:
    path:     /{id}/update
    defaults: { _controller: "UbicacionBundle:Pais:update" }
    requirements: { _method: post|put }

pais_delete:
    path:     /{id}/delete
    defaults: { _controller: "UbicacionBundle:Pais:delete" }
    requirements: { _method: post|delete }
