personas_categoria_empleado:
    resource: "@PersonasBundle/Resources/config/routing/categoriaempleado.yml"
    prefix:   /categoria_empleado

personas_categoria_empleado:
    resource: "@PersonasBundle/Resources/config/routing/categoriaempleado.yml"
    prefix:   /categoria_empleado

personas_empleados:
    resource: "@PersonasBundle/Resources/config/routing/empleado.yml"
    prefix:   /empleados

personas_tipos_documento:
    resource: "@PersonasBundle/Resources/config/routing/tipodocumento.yml"
    prefix:   /tipos_documento

personas_personas:
    resource: "@PersonasBundle/Resources/config/routing/persona.yml"
    prefix:   /personas

buscar_persona:
    path:     /buscar_persona
    defaults: { _controller: "PersonasBundle:Default:buscarPersona" }


personas_homepage:
    path:     /hello/{name}
    defaults: { _controller: PersonasBundle:Default:index }
