services:
#    personas.example:
#        class: PersonasBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    manager.personas:
        class: PersonasBundle\Services\PersonasManager
        arguments:
            container: '@service_container'
            tags:
                - { name: manager.personas, alias: manager.personas }