cuestionarios_encuesta_opcion_respuesta:
    resource: "@CuestionariosBundle/Resources/config/routing/encuestaopcionrespuesta.yml"
    prefix:   /encuesta_opcion_respuesta

cuestionarios_encuesta_pregunta:
    resource: "@CuestionariosBundle/Resources/config/routing/encuestapregunta.yml"
    prefix:   /encuesta_pregunta

cuestionarios_preguntas:
    resource: "@CuestionariosBundle/Resources/config/routing/cuestionariopregunta.yml"
    prefix:   /preguntas

cuestionarios_categorias_cuestionario:
    resource: "@CuestionariosBundle/Resources/config/routing/cuestionariocategoria.yml"
    prefix:   /categorias_cuestionario

cuestionarios_tipo_pregunta:
    resource: "@CuestionariosBundle/Resources/config/routing/tipopregunta.yml"
    prefix:   /tipo_pregunta

cuestionarios_cuestionarios:
    resource: "@CuestionariosBundle/Resources/config/routing/cuestionario.yml"
    prefix:   /
