ajax_crm_cantidad_llamadas_no_concretadas:
    path:     /cantidad_llamadas_no_concretadas
    defaults: { _controller: "CRMBundle:Ajax:getCantidadLlamadasNoConcretadas" }

ajax_crm_post_llamadas_no_concretadas:
    path:     /llamadas_no_concretadas/{id}/{encuestaId}
    defaults: { _controller: "CRMBundle:Ajax:llamadasNoConcretadas" }

ajax_crm_get_encuesta:
    path:     /get_encuestas/{id}
    defaults: { _controller: "CRMBundle:Ajax:getEncuestas" }