<?php

namespace CuestionariosBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CuestionarioCategoriaRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class CuestionarioCategoriaRepository extends EntityRepository
{
    public function getCategoriasConCampos($cuestionario)
    {
        $qb = $this->createQueryBuilder('cc');
        $qb->join('cc.cuestionario', 'cuest')
            ->where('cc.preguntas is not empty')
            ->andWhere('cuest = :cuestionario')
            ->orderBy('cc.orden', 'ASC');
        $qb->setParameter('cuestionario', $cuestionario);

        return $qb->getQuery()->getResult();
    }
}
