services:
#    usuarios.example:
#        class: UsuariosBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    usuario.form.group:
        class: UsuariosBundle\Form\GrupoType
        tags:
            - { name: form.type, alias: usuarios_bundle_grupo_type }

    manager.permisos:
            class: UsuariosBundle\Services\PermisosManager
            arguments:
                em: '@doctrine.orm.entity_manager'
                router: '@router'
            tags:
                - { name: manager.permisos, alias: manager.permisos }

    logiautos_user.login:
        class: UsuariosBundle\EventListener\LoginListener
        arguments: ['@service_container']
        tags:
            - { name: kernel.event_subscriber }